{% set name = "predictr" %}
{% set version = "0.1.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/predictr-{{ version }}.tar.gz
  sha256: e5fca708bc0233a794d17878ccefc2736645cf92802e9e7ac3aac9d272e8d2e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=2.2.0
    - numpy >=1.16.0
    - pandas >=1.0.0
    - python >=3.6
    - scipy >=1.3.0

test:
  imports:
    - predictr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://tvtoglu.github.io/predictr/
  summary: Life Data Analysis for Reliability Engineers - Weibull Analysis, Detailed Plots, Compute Statistics
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://tvtoglu.github.io/predictr/classes/
  dev_url: https://github.com/tvtoglu/predictr

extra:
  recipe-maintainers:
    - melonhead901
